### ISSUE TITLE
Consolidate widgets and update the widget_map.yml file

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#136]
The goal here is to remove the redundant widgets and just leave the core widgets. The widgets I want to deprecate are:

custom-page: About Us
link: blog, donate, event calendar, flickr, photo bucket, news, picasa, reviews, video
products: services

**Comment by gilbert** [comment]
`widget_maps.yml` specifies which widgets sites will get; it should not be a place to specify widgets themselves. What needs to be done is moving the data from `couch_docs.rb:114` to its own `.yml` file. We'll call it `widgets.yml`.

You're wanting to specify custom widgets that will be available to one site type and not another, correct? I suggest we create widget **aliases**. Aliases will not appear in the sidebar list of available widgets.

`widgets.yml` will look something like this:

```
widgets:
  -
    wtype: booking
    name: Booking Request
    singleton: true
    email: nil
    help: "<p>Allow your mobile site visitors..."
  -
    wtype: link
    name: Link
    help: "<p>Add a link to another website on..."
aliases:
  -
    wtype: link
    alias: donate
    name: Donate
    help: "<p>Add a link to your online donation page.</p>"
```

Then, in `widget_maps.yml`, you can reference the alias widget:

```
docs:
  -
    types:
      - Airport
    widgets:
      - custom_page
      - donate
      ...
    tabs:
      ...
```

What do you think?
